# Generated by Django 5.2.1 on 2025-05-19 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Eidikotita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eidikotita_pliris",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Πλήρης Ονομασία Ειδικότητας",
                    ),
                ),
                (
                    "eidikotita_sintomi",
                    models.CharField(
                        max_length=50,
                        verbose_name="Σύντομη Ονομασία Ειδικότητας (π.χ. ΔΕ1)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ειδικότητα",
                "verbose_name_plural": "Ειδικότητες",
                "ordering": ["eidikotita_sintomi"],
            },
        ),
        migrations.CreateModel(
            name="EidosProypiresias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perigrafi",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Περιγραφή Είδους Προϋπηρεσίας",
                    ),
                ),
            ],
            options={
                "verbose_name": "Είδος Προϋπηρεσίας",
                "verbose_name_plural": "Είδη Προϋπηρεσιών",
                "ordering": ["perigrafi"],
            },
        ),
        migrations.CreateModel(
            name="SxesiErgasias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perigrafi",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Περιγραφή Σχέσης Εργασίας",
                    ),
                ),
            ],
            options={
                "verbose_name": "Σχέση Εργασίας",
                "verbose_name_plural": "Σχέσεις Εργασίας",
                "ordering": ["perigrafi"],
            },
        ),
        migrations.CreateModel(
            name="Ypiresia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "onomasia",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Ονομασία Υπηρεσίας"
                    ),
                ),
            ],
            options={
                "verbose_name": "Υπηρεσία Τοποθέτησης/Υπηρέτησης",
                "verbose_name_plural": "Υπηρεσίες Τοποθέτησης/Υπηρέτησης",
                "ordering": ["onomasia"],
            },
        ),
        migrations.CreateModel(
            name="Ekpaideftikos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("onoma", models.CharField(max_length=100, verbose_name="Όνομα")),
                ("eponymo", models.CharField(max_length=100, verbose_name="Επώνυμο")),
                (
                    "patronymo",
                    models.CharField(max_length=100, verbose_name="Πατρώνυμο"),
                ),
                (
                    "tilefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Τηλέφωνο"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "eidikotita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proypiresies_app.eidikotita",
                        verbose_name="Ειδικότητα",
                    ),
                ),
            ],
            options={
                "verbose_name": "Εκπαιδευτικός",
                "verbose_name_plural": "Εκπαιδευτικοί",
                "ordering": ["eponymo", "onoma"],
                "unique_together": {("onoma", "eponymo", "patronymo", "eidikotita")},
            },
        ),
        migrations.CreateModel(
            name="Aitisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sxoliko_etos",
                    models.CharField(
                        max_length=9, verbose_name="Σχολικό Έτος (π.χ. 2024-25)"
                    ),
                ),
                (
                    "typos_ekpaideftikou",
                    models.CharField(
                        choices=[
                            ("MONIMOS", "Μόνιμος"),
                            ("ANAPLIROTIS", "Αναπληρωτής"),
                        ],
                        max_length=20,
                        verbose_name="Τύπος Εκπαιδευτικού",
                    ),
                ),
                (
                    "imerominia_ypovolis",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Ημερομηνία Υποβολής Αίτησης",
                    ),
                ),
                (
                    "arxeio_aitisis_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="aitiseis_pdf/%Y/%m/",
                        verbose_name="Αρχείο Αίτησης (PDF)",
                    ),
                ),
                (
                    "se_anamoni",
                    models.BooleanField(
                        default=False, verbose_name="Σε Αναμονή Δικαιολογητικών"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ημερομηνία Δημιουργίας"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ημερομηνία Ενημέρωσης"
                    ),
                ),
                (
                    "ekpaideftikos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proypiresies_app.ekpaideftikos",
                        verbose_name="Εκπαιδευτικός",
                    ),
                ),
            ],
            options={
                "verbose_name": "Αίτηση Αναγνώρισης Προϋπηρεσίας",
                "verbose_name_plural": "Αιτήσεις Αναγνώρισης Προϋπηρεσιών",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Proypiresia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arithmos_protokollou_vevaiosis",
                    models.CharField(
                        default="ΟΠΣΥΔ",
                        max_length=100,
                        verbose_name="Αρ. Πρωτοκόλλου/Βεβ. Προϋπηρεσίας",
                    ),
                ),
                (
                    "xroniko_diastima_apo",
                    models.DateField(verbose_name="Χρονικό Διάστημα ΑΠΟ"),
                ),
                (
                    "xroniko_diastima_eos",
                    models.DateField(verbose_name="Χρονικό Διάστημα ΕΩΣ"),
                ),
                (
                    "eti_proypiresias",
                    models.PositiveIntegerField(default=0, verbose_name="Έτη"),
                ),
                (
                    "mines_proypiresias",
                    models.PositiveIntegerField(default=0, verbose_name="Μήνες"),
                ),
                (
                    "meres_proypiresias",
                    models.PositiveIntegerField(default=0, verbose_name="Μέρες"),
                ),
                (
                    "paratiriseis",
                    models.TextField(
                        blank=True, null=True, verbose_name="Παρατηρήσεις"
                    ),
                ),
                (
                    "esoterikes_simeioseis",
                    models.TextField(
                        blank=True, null=True, verbose_name="Εσωτερικές Σημειώσεις"
                    ),
                ),
                (
                    "elegxthike",
                    models.BooleanField(default=False, verbose_name="Ελέγχθηκε"),
                ),
                (
                    "elegxthike_pote",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ελέγχθηκε στις"
                    ),
                ),
                (
                    "paravlepsi",
                    models.BooleanField(
                        default=False, verbose_name="Παράβλεψη (δεν υπολογίζεται)"
                    ),
                ),
                (
                    "aitisi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proypiresies",
                        to="proypiresies_app.aitisi",
                        verbose_name="Αίτηση",
                    ),
                ),
                (
                    "eidos_proypiresias",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proypiresies_app.eidosproypiresias",
                        verbose_name="Είδος Προϋπηρεσίας (από λίστα)",
                    ),
                ),
                (
                    "elegxthike_apo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elegxmenes_proypiresies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ελέγχθηκε από",
                    ),
                ),
                (
                    "sxesi_ergasias",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proypiresies_app.sxesiergasias",
                        verbose_name="Σχέση Εργασίας (από λίστα)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Καταχωρημένη Προϋπηρεσία",
                "verbose_name_plural": "Καταχωρημένες Προϋπηρεσίες",
                "ordering": ["aitisi", "xroniko_diastima_apo"],
            },
        ),
        migrations.CreateModel(
            name="PYSEEP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arithmos_praxis",
                    models.CharField(
                        max_length=50, verbose_name="Αριθμός Πράξης ΠΥΣΕΕΠ"
                    ),
                ),
                (
                    "imerominia_praxis",
                    models.DateField(verbose_name="Ημερομηνία Πράξης ΠΥΣΕΕΠ"),
                ),
            ],
            options={
                "verbose_name": "Πράξη ΠΥΣΕΕΠ",
                "verbose_name_plural": "Πράξεις ΠΥΣΕΕΠ",
                "ordering": ["-imerominia_praxis", "arithmos_praxis"],
                "unique_together": {("arithmos_praxis", "imerominia_praxis")},
            },
        ),
        migrations.AddField(
            model_name="aitisi",
            name="pyseep_proothisis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aitiseis_proothisis",
                to="proypiresies_app.pyseep",
                verbose_name="Έτοιμη για ΠΥΣΕΕΠ (Προώθηση)",
            ),
        ),
        migrations.AddField(
            model_name="aitisi",
            name="pyseep_teliki_apofasi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aitiseis_telikes_apofaseis",
                to="proypiresies_app.pyseep",
                verbose_name="Τελική Απόφαση από ΠΥΣΕΕΠ",
            ),
        ),
        migrations.AddField(
            model_name="aitisi",
            name="ypiresia_trexousas_topothetisis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="proypiresies_app.ypiresia",
                verbose_name="Υπηρεσία Τρέχουσας Τοποθέτησης",
            ),
        ),
        migrations.CreateModel(
            name="ProypiresiaPyseepHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imerominia_egkrisis_apo_pyseep",
                    models.DateField(verbose_name="Ημερομηνία Έγκρισης από ΠΥΣΕΕΠ"),
                ),
                (
                    "proypiresia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pyseep_history_entries",
                        to="proypiresies_app.proypiresia",
                        verbose_name="Προϋπηρεσία",
                    ),
                ),
                (
                    "pyseep_apofasis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proypiresies_app.pyseep",
                        verbose_name="ΠΥΣΕΕΠ Απόφασης",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ιστορικό Έγκρισης Προϋπηρεσίας από ΠΥΣΕΕΠ",
                "verbose_name_plural": "Ιστορικά Εγκρίσεων Προϋπηρεσιών από ΠΥΣΕΕΠ",
                "ordering": ["proypiresia", "-imerominia_egkrisis_apo_pyseep"],
                "unique_together": {("proypiresia", "pyseep_apofasis")},
            },
        ),
    ]
